import type { ServiceDetail } from './types';

export const SERVICES: ServiceDetail[] = [
  {
    slug: 'web-development',
    num: '01',
    icon: '🌐',
    title: 'Web Development',
    tagline: 'Websites that convert visitors into clients.',
    shortDesc: 'Fast, responsive, scalable websites built for real business performance — from design to deployment.',
    fullDesc: `Your website is your most powerful sales tool — or your biggest missed opportunity. At Autonex AI, we build high-performance websites that do more than look good: they load fast, rank on search engines, and turn visitors into qualified leads and paying customers.\n\nWe combine sharp UI/UX design with modern full-stack engineering to deliver sites that are as technically solid as they are visually compelling. Every project is scoped, designed, and built from scratch around how your business actually works — not a template retrofitted to fit.`,
    image: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=1200&q=80&fm=webp&auto=format',
    includes: [
      'Custom UI/UX Design (wireframes to production code)',
      'Full-stack web development (custom architecture)',
      'SEO-optimised structure, metadata & schema markup',
      'Content management system integration',
      'Performance optimisation (Core Web Vitals)',
      'Analytics & conversion tracking setup',
      'Hosting configuration & deployment',
      '30-day post-launch support',
    ],
    process: [
      { step: 'Discovery & Goals', desc: 'We understand your brand, audience, and conversion objectives before a single pixel is placed.' },
      { step: 'Wireframes & Design', desc: 'We design every screen and present them for your approval before development begins.' },
      { step: 'Development', desc: 'Clean, modern code with performance and SEO baked in from line one.' },
      { step: 'QA & Testing', desc: 'Full cross-browser, cross-device testing. Speed audits. Accessibility checks.' },
      { step: 'Launch & Handover', desc: 'We deploy, hand over full documentation, and train your team on the content system.' },
    ],
    whoFor: [
      'Startups launching their first professional website',
      'Growing businesses with an outdated or slow website',
      'Companies losing leads due to poor UX or mobile experience',
      'Founders who want a website that drives real business results',
    ],
    outcomes: [
      'Faster page loads that reduce bounce rate',
      'Higher search engine rankings through technical SEO',
      'More leads captured through smart conversion design',
      'A website your team can manage without developer help',
    ],
  },
  {
    slug: 'ai-sales-support-agents',
    num: '02',
    icon: '💬',
    title: 'AI Sales & Support Agents',
    tagline: 'A sales team that never sleeps.',
    shortDesc: 'Intelligent AI agents that qualify leads, book appointments, and support customers — 24/7.',
    fullDesc: `What if your business could respond to every lead, answer every question, and book every meeting — even at 2am on a Sunday? That's what Autonex AI's custom sales and support agents do.\n\nWe build AI agents trained specifically on your products, services, pricing, and processes. They handle inbound enquiries across your website, messaging platforms, and email — qualifying leads, booking calls directly into your calendar, and routing complex queries to your human team when needed. No hallucinations. No generic responses. Just your business, running at full capacity around the clock.`,
    image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=1200&q=80&fm=webp&auto=format',
    includes: [
      'Custom AI agent trained on your business data',
      'Multi-channel deployment (website, messaging apps, email)',
      'CRM & calendar integration',
      'Lead qualification with scoring logic',
      'Live handoff to human agents when needed',
      'Conversation analytics & performance dashboard',
      'Ongoing model updates & retraining',
    ],
    process: [
      { step: 'Knowledge Base Setup', desc: 'We document your FAQs, products, pricing, and objection handling — this becomes the agent\'s brain.' },
      { step: 'Agent Training & Configuration', desc: 'We build and train the AI model on your specific business context and tone of voice.' },
      { step: 'Integration & Testing', desc: 'Connect to your CRM, calendar, and channels. Stress-test with hundreds of edge cases.' },
      { step: 'Deployment & Monitoring', desc: 'Go live across your chosen platforms with full visibility into every conversation.' },
      { step: 'Iteration & Improvement', desc: 'Monthly reviews of conversation data to refine responses and improve conversion rates.' },
    ],
    whoFor: [
      'Businesses missing leads outside office hours',
      'Sales teams spending too much time on unqualified enquiries',
      'E-commerce stores with repetitive support queries',
      'Service businesses that rely on bookings and appointments',
    ],
    outcomes: [
      '24/7 lead capture and qualification',
      'Significant reduction in support ticket volume',
      'More booked calls without increasing headcount',
      'Faster response times — measured in seconds, not hours',
    ],
  },
  {
    slug: 'ai-lead-generation',
    num: '03',
    icon: '🎯',
    title: 'AI Lead Generation & Outreach',
    tagline: 'Fill your pipeline. Automatically.',
    shortDesc: 'Automated systems that find your ideal prospects, craft personalised messages, and build your sales pipeline on autopilot.',
    fullDesc: `Cold outreach is broken — because most of it is generic. Prospects receive hundreds of identical emails every week. The only way to cut through is with genuine relevance at scale, and that's only possible with AI.\n\nAutonex AI builds outreach systems that research each prospect individually, craft personalised messages based on their role, company, and recent activity, and send those messages at the right time through the right channel. The result: a consistent, qualified pipeline without cold calling or manual prospecting.`,
    image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&q=80&fm=webp&auto=format',
    includes: [
      'Ideal Customer Profile (ICP) definition & research',
      'Automated prospect identification & data enrichment',
      'AI-personalised email sequence writing',
      'Social & professional network outreach automation',
      'Multi-touch follow-up sequences',
      'Reply detection & intelligent routing',
      'CRM pipeline integration & tracking',
      'Performance analytics & A/B testing',
    ],
    process: [
      { step: 'ICP & Targeting', desc: 'We work with you to define exactly who your best clients are, then build a targeting framework around that.' },
      { step: 'Data & Enrichment', desc: 'We source and enrich prospect data from multiple verified sources — no buying lists.' },
      { step: 'Message Framework', desc: 'AI-assisted copywriting with your brand voice, personalised variables, and tested subject lines.' },
      { step: 'Sequence Build & Launch', desc: 'Multi-touch sequences across email and professional networks, configured with smart delays and triggers.' },
      { step: 'Optimise & Scale', desc: 'Weekly reporting on open rates, replies, and pipeline generated. Continuous optimisation.' },
    ],
    whoFor: [
      'B2B businesses without a consistent outbound pipeline',
      'Founders spending too much time on manual prospecting',
      'Sales teams that need qualified leads, not just contacts',
      'Agencies looking to scale client acquisition',
    ],
    outcomes: [
      'A consistent flow of qualified leads every week',
      'Higher reply rates through genuine personalisation',
      'Zero time spent on manual research or list building',
      'Full pipeline visibility inside your existing CRM',
    ],
  },
  {
    slug: 'ai-content-systems',
    num: '04',
    icon: '✍️',
    title: 'AI Content Systems',
    tagline: 'Publish more. Work less.',
    shortDesc: 'AI-powered workflows that produce blogs, social posts, newsletters, and marketing copy in your brand voice — at scale.',
    fullDesc: `Content marketing works. The problem is it takes time — time that most growing businesses don't have. Autonex AI builds AI content systems that turn a single strategy session into weeks of high-quality, on-brand content across every channel.\n\nWe train AI on your brand voice, tone, and audience — then build automated workflows that produce, edit, and schedule content without the bottlenecks. The output isn't generic AI filler; it's strategic content that sounds like you, ranks on search engines, and moves your audience toward a decision.`,
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=1200&q=80&fm=webp&auto=format',
    includes: [
      'Brand voice training & content guidelines',
      'Blog & long-form article generation system',
      'Social media content calendar automation',
      'Email newsletter workflow',
      'SEO content brief generation',
      'Content approval & scheduling pipeline',
      'Performance tracking & iteration',
    ],
    process: [
      { step: 'Brand Voice Audit', desc: 'We analyse your existing content and define your tone, style, and voice guidelines for the AI.' },
      { step: 'Content Strategy', desc: 'Map out content pillars, topics, and distribution channels aligned with your business goals.' },
      { step: 'System Build', desc: 'Build the automated workflows that produce, format, and prepare content for review.' },
      { step: 'Integration & Scheduling', desc: 'Connect to your content management system, email platform, and social scheduler to automate the distribution pipeline.' },
      { step: 'Review & Refine', desc: 'Monthly content performance review. Continuous AI model updates based on what works.' },
    ],
    whoFor: [
      'Businesses struggling to publish content consistently',
      'Founders who know content matters but don\'t have time',
      'Marketing teams with limited writing resources',
      'Agencies managing content for multiple clients',
    ],
    outcomes: [
      '10× more content output without 10× more effort',
      'Consistent brand voice across every channel',
      'Better search engine rankings through regular, quality content',
      'A content machine that runs in the background while you focus on growth',
    ],
  },
  {
    slug: 'crm-operations-automation',
    num: '05',
    icon: '⚙️',
    title: 'CRM & Operations Automation',
    tagline: 'Your business runs itself.',
    shortDesc: 'Custom CRM builds, tool integrations, and automated workflows — designed around how your business actually operates.',
    fullDesc: `The average growing business has 10–20 tools that don't talk to each other. Data lives in spreadsheets, tasks fall through the cracks, and your team spends hours each week on manual data entry that should never happen.\n\nAutonex AI designs and builds custom CRM systems and operational workflows tailored specifically to your business — not off-the-shelf platforms retrofitted to fit. We map your entire operational workflow, then build the automation infrastructure that makes your business run like a machine — with no manual effort and no missed steps.`,
    image: 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=1200&q=80&fm=webp&auto=format',
    includes: [
      'Full workflow audit & process mapping',
      'Custom CRM design & development',
      'Tool integration & automation pipelines',
      'Client onboarding automation',
      'Invoice & billing automation',
      'Team notification & task assignment systems',
      'Automated reporting pipelines',
      'Documentation & training handover',
    ],
    process: [
      { step: 'Workflow Discovery', desc: 'We map every manual process in your business — from lead to invoice — to find automation opportunities.' },
      { step: 'Priority Ranking', desc: 'We rank automations by time saved × frequency to build your highest-ROI system first.' },
      { step: 'Build & Integrate', desc: 'We build your custom CRM and connect automations across your existing tools — no unnecessary replacements.' },
      { step: 'Testing & QA', desc: 'End-to-end testing of every workflow with real data to eliminate errors before launch.' },
      { step: 'Training & Handover', desc: 'Full documentation and team training so you understand and own every system we build.' },
    ],
    whoFor: [
      'Businesses with too many tools and too little integration',
      'Teams spending hours on manual data entry each week',
      'Founders who feel like their business runs them, not the other way around',
      'Operations managers looking to reduce human error and speed up processes',
    ],
    outcomes: [
      'Significant reduction in time spent on manual tasks',
      'Zero data falling between tools',
      'Faster onboarding, faster reporting, faster everything',
      'A business that scales without adding administrative headcount',
    ],
  },
  {
    slug: 'ai-voice-agents',
    num: '06',
    icon: '📞',
    title: 'AI Voice Agents & Phone Automation',
    tagline: 'Never miss a call again.',
    shortDesc: 'AI voice systems that handle calls, book appointments, answer FAQs, and route enquiries in natural, conversational speech.',
    fullDesc: `Phone calls are still one of the highest-converting touchpoints in business — but most businesses are missing them. After hours, during busy periods, or when the team is overwhelmed, calls go to voicemail and leads go cold.\n\nAutonex AI builds AI voice agents that answer calls with natural, conversational speech, handle inbound enquiries intelligently, and book appointments directly into your calendar — without a human ever picking up. For outbound, we build follow-up systems that re-engage leads automatically, increasing booked meetings without adding to your team's workload.`,
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80&fm=webp&auto=format',
    includes: [
      'Custom AI voice agent build & training',
      'Inbound call handling & intelligent routing',
      'Appointment booking with live calendar sync',
      'Outbound follow-up call automation',
      'Call transcription & CRM logging',
      'FAQ handling with escalation paths',
      'Performance dashboard & call analytics',
    ],
    process: [
      { step: 'Call Flow Mapping', desc: 'We document your typical inbound and outbound call scenarios — questions, objections, booking flows.' },
      { step: 'Voice Agent Configuration', desc: 'We build your AI voice agent with the right tone, personality, and knowledge base for your business.' },
      { step: 'Integration & Testing', desc: 'Connect to your phone system, calendar, and CRM. Test with hundreds of real call scenarios.' },
      { step: 'Go Live & Monitor', desc: 'Deploy the agent on your phone number with real-time monitoring and instant escalation paths.' },
      { step: 'Iteration & Improvement', desc: 'Monthly review of call transcripts and booking rates to continuously refine the agent.' },
    ],
    whoFor: [
      'Businesses missing calls outside of working hours',
      'Service businesses that rely on booked appointments',
      'Sales teams that need consistent outbound follow-up',
      'Companies with high-volume inbound call centres',
    ],
    outcomes: [
      '100% of calls answered — day or night',
      'More appointments booked without more staff',
      'Consistent, professional call handling every time',
      'Full call logs and transcripts for every conversation',
    ],
  },
  {
    slug: 'ai-reporting-intelligence',
    num: '07',
    icon: '📊',
    title: 'AI Reporting & Business Intelligence',
    tagline: 'Know exactly where you stand.',
    shortDesc: 'Custom dashboards that pull live data from all your tools and surface the KPIs that actually matter.',
    fullDesc: `Most businesses are making decisions with incomplete or outdated data. Spreadsheets are hours old before they\'re read. Dashboards show vanity metrics rather than the numbers that drive decisions.\n\nAutonex AI builds custom reporting systems that connect to every tool you use — your CRM, website, advertising accounts, email platform, and finance tools — and surface real-time KPIs in a single, clean dashboard. You stop waiting for reports and start making faster, smarter decisions based on what's actually happening right now.`,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80&fm=webp&auto=format',
    includes: [
      'Business KPI discovery & definition',
      'Multi-source data integration (CRM, ads, web, finance)',
      'Custom dashboard design & build',
      'Automated weekly/monthly reporting',
      'Alert systems for key metric changes',
      'Trend analysis & performance benchmarking',
      'Team performance tracking',
    ],
    process: [
      { step: 'KPI Discovery', desc: 'We work with leadership to define the 10–15 metrics that truly drive your business decisions.' },
      { step: 'Data Source Mapping', desc: 'Identify every tool and platform that contains relevant data — then plan the integration architecture.' },
      { step: 'Dashboard Build', desc: 'Build your custom dashboard with live data connectors, clean visualisations, and intuitive layout.' },
      { step: 'Alert Configuration', desc: 'Set up automated alerts for when key metrics move above or below defined thresholds.' },
      { step: 'Team Onboarding', desc: 'Train your team to use the dashboard for weekly decision-making. Documentation included.' },
    ],
    whoFor: [
      'Founders making decisions without reliable, real-time data',
      'Operations teams spending hours building manual reports',
      'Businesses with data spread across multiple disconnected tools',
      'Leadership teams that need clear visibility across departments',
    ],
    outcomes: [
      'Real-time visibility into the metrics that matter',
      'Zero time spent building manual reports',
      'Faster decisions based on accurate, live data',
      'Early warning systems that surface problems before they escalate',
    ],
  },
  {
    slug: 'document-processing-ai',
    num: '08',
    icon: '🗂️',
    title: 'Document Processing & Workflow AI',
    tagline: 'Paperwork runs itself.',
    shortDesc: 'Intelligent document automation that extracts data, routes approvals, and eliminates bottlenecks in document-heavy workflows.',
    fullDesc: `Documents are one of the biggest drains on business productivity. Contracts, invoices, applications, compliance forms — every document requires someone to read it, extract data from it, route it to the right person, and chase approval. For most businesses, this is hours of work every week.\n\nAutonex AI builds intelligent document processing systems that read, classify, and extract data from documents automatically — then trigger the right workflow: route for approval, populate your CRM, generate a response, or flag exceptions. The result is a document workflow that runs end-to-end without human intervention for standard cases.`,
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80&fm=webp&auto=format',
    includes: [
      'Document type identification & classification',
      'OCR & intelligent data extraction',
      'Automated approval routing workflows',
      'Form processing & data population',
      'Exception handling & human escalation paths',
      'Compliance tracking & audit trails',
      'Integration with your existing document tools',
    ],
    process: [
      { step: 'Document Audit', desc: 'We map every document type in your business and the manual steps currently involved in processing them.' },
      { step: 'Extraction Model Build', desc: 'We configure and train AI models to accurately extract the specific data fields you need from each document type.' },
      { step: 'Workflow Configuration', desc: 'Build the downstream automation: what happens after data is extracted — routing, population, notifications.' },
      { step: 'Integration & Testing', desc: 'Connect to your document storage, CRM, and approval tools. Test with hundreds of real document samples.' },
      { step: 'Handover & Monitoring', desc: 'Deploy with full monitoring. Clear exception paths for documents the AI flags for human review.' },
    ],
    whoFor: [
      'Businesses processing high volumes of documents manually',
      'Legal, finance, or compliance teams buried in paperwork',
      'Companies with slow, bottlenecked approval processes',
      'Operations teams spending hours on data entry from documents',
    ],
    outcomes: [
      'Dramatic reduction in manual document handling time',
      'Faster approval cycles and reduced bottlenecks',
      'Near-zero manual data entry errors',
      'Full audit trail and compliance documentation',
    ],
  },
];

export function getServiceBySlug(slug: string): ServiceDetail | undefined {
  return SERVICES.find(s => s.slug === slug);
}

export function getAllServiceSlugs(): string[] {
  return SERVICES.map(s => s.slug);
}
